FROM node:alpine
COPY . /App
WORKDIR /App
CMD node App.js

# docker commands
# docker build -t docker-tutorial . - to build a docker image in the current folder
# docker images - show the current images in docker
# docker image rm <image name>:<specify version>
# docker run <name of the image>
# docker run ubuntu - start a docker container 
# docker run -it -d <container id> - to create and run a docker file
# docker exec -it <container id> - to run an existing docker file
# docker ps - check running processes
# docker ps -a - check all processes
# docker run -it ubuntu - start ubuntu container
