apiVersion: v1 # folder that contains certain resources that we can use
kind: Pod
metadata: # labelling our resource
  name: client-pod
  labels: # tag to enable us to interact with our pod i.e service with a pod
    app: client
spec: # specifications of our resource
  containers:
  - name: client
    image: laithharb/web-app # imageinourdockerhub:version(optional)
    imagePullPolicy: Never
  restartPolicy: Always
  dnsPolicy: ClusterFirst
